name: Commit version
description: Commit version

inputs:
  version:
    description: Version
    required: true
  github_token:
    description: The token to use to authenticate to the github
    required: true
  branch_name:
    required: true
    description: The branch to commit
runs:
  using: composite

  steps:
    - name: Set develop environment variables
      if: ${{ inputs.branch_name == 'develop' }}
      run: |
        echo "ENVIRONMENT=develop" >> $GITHUB_ENV
      shell: bash

    - name: Set production environment variables
      if: ${{ inputs.branch_name == 'master' || inputs.branch_name == 'main' }}
      run: |
        echo "ENVIRONMENT=pro" >> $GITHUB_ENV
      shell: bash

    - name: Update version in kustomization.yaml
      uses: fjogeleit/yaml-update-action@main
      if: ${{ env.ENVIRONMENT != null}}
      with:
        valueFile: "deploy/${{ env.ENVIRONMENT }}/kustomization.yaml"
        propertyPath: 'images[0].newTag'
        value: ${{ inputs.version }}
        commitChange: false
        createPR: false
    - name: Update DD_VERSION in values.yaml
      uses: fjogeleit/yaml-update-action@main

      if: ${{ inputs.branch_name == 'develop' }}
      with:
        valueFile: "deploy/${{ env.ENVIRONMENT }}/values.yaml"
        # it's the first element in the list of env variables
        propertyPath: 'spec.template.spec.containers[0].env[0].value'
        value: ${{ inputs.version }}
        commitChange: true
        message: "build: automatic update - DD_VERSION to ${{ inputs.version }}"
        branch: ${{ inputs.branch_name }}
        token: ${{ inputs.github_token }}
        createPR: false
        commitUserName: playtomic-bot
        commitUserEmail: playtomic-bot@playtomic.io