name: Commit version
description: Commit version

inputs:
  version:
    description: Version
    required: true
  github_token:
    description: The token to use to authenticate to the github
    required: true
  branch_name:
    required: true
    description: The branch to commit
runs:
  using: composite

  steps:
    - name: Set develop environment variables
      if: ${{ inputs.branch_name == 'develop' }}
      run: |
        echo "ENVIRONMENT=develop" >> $GITHUB_ENV
      shell: bash

    - name: Set production environment variables
      if: ${{ inputs.branch_name == 'master' || inputs.branch_name == 'main' }}
      run: |
        echo "ENVIRONMENT=pro" >> $GITHUB_ENV
      shell: bash

    - name: Update versions in values.yaml and kustomization.yaml
      uses: fjogeleit/yaml-update-action@main

      if: ${{ inputs.branch_name == 'develop' }}
      with:
        title: 'Version Updates '
        changes: |
          {
            "deploy/${{ env.ENVIRONMENT }}/kustomization.yaml": {
              "images[0].newTag": "${{ inputs.version }}"
            },
            "deploy/${{ env.ENVIRONMENT }}/values-datadog.yaml" : {
              "spec.template.spec.containers[0].env[0].value": "${{ inputs.version }}"
            }
          }
        commitChange: true
        message: "build: automatic update - versions  to ${{ inputs.version }} [skip ci]"
        branch: ${{ inputs.branch_name }}
        token: ${{ inputs.github_token }}
        createPR: false
        commitUserName: playtomic-bot
        commitUserEmail: playtomic-bot@playtomic.io