name: Docker Build
description: Build docker images

inputs:
  version:
    description: Version of the image
    required: true
  container_repository:
    description: The container repository to store the image
    required: false
    default: 'nexus'
  dockernexus_username:
    description: The username to use to authenticate to the docker nexus
    required: true
  dockernexus_token:
    description: The token to use to authenticate to the docker nexus
    required: true
  github_token:
    description: The token to use to authenticate to the github
    required: true

outputs:
  docker_repository:
    description: The docker repository used
    value: ${{ env.DOCKER_REPOSITORY }}

runs:
  using: composite

  steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Nexus environment
      if: ${{ inputs.container_repository == 'nexus' }}
      run: |
        echo "REGISTRY=nexus.playtomic.io" >> $GITHUB_ENV
        echo "IMAGE=nexus.playtomic.io/${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "DOCKER_REPOSITORY=nexus.playtomic.io" >> $GITHUB_ENV
        echo "DOCKER_USERNAME=${{ inputs.dockernexus_username }}" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=${{ inputs.dockernexus_token }}" >> $GITHUB_ENV
      shell: bash

    - name: GHCR environment
      if: ${{ inputs.container_repository == 'ghcr' }}
      run: |
        echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
        echo "IMAGE=nexus.playtomic.io/${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "DOCKER_REPOSITORY=ghcr.io/${{ github.repository_owner }}" >> $GITHUB_ENV  
        echo "DOCKER_USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=${{ inputs.github_token }}" >> $GITHUB_ENV
      shell: bash

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE }}
        tags: |
          type=raw,value=${{ inputs.version }}
          type=raw,value=latest

    - name: Build and push
      uses: docker/bake-action@v1.7.0
      with:
        files: |
          ${{ steps.meta.outputs.bake-file }}
          docker-compose.yml
        push: true
        set: |
          *.cache-from=type=registry,ref=${{ github.repository }}:latest
          *.cache-to=type=inline
