name: Anemone Version
description: Generate version for Anemone Service

inputs:
  branch_name:
    required: true
    description: The branch to put in the version

outputs:
  version:
    description: The version of the service
    value: ${{ steps.version.outputs.replaced }}

runs:
  using: composite

  steps:
    - name: Get date
      id: date
      run: echo "date=$(date +'%Y%m%d%H%M%S')" >> GITHUB_OUTPUT
      shell: bash

    - name: Version
      id: version
      run: echo "replaced=$(echo ${{inputs.branch_name}}-${{steps.date.outputs.date}}-${{github.run_number}}-${{github.sha}}  | sed 's/\//-/g')" >> GITHUB_OUTPUT
      shell: bash
