# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy Anemone services

on:
  workflow_call:
    secrets:
      nexus_user:
        required: true
        description: User to login into Nexus mvn
      nexus_password:
        required: true
        description: Password to login into Nexus
      dockernexus_username:
        required: true
        description: Username to login into Nexus
      dockernexus_token:
        required: true
        description: Password to login into Nexus
      aws_docker_host_dev:
        required: true
        description: URL of the aws docker host in develop
      aws_docker_host_pro:
        required: true
        description: URL of the aws docker host in pro
      playtomic_bot_app_private_key:
        required: true
        description: The private key to generate our auth token (most likely PLAYTOMIC_BOT_APP_PRIVATE_KEY)
    inputs:
      java_version:
        required: true
        description: Java version to use
        type: string
      replicas:
        required: false
        description: The number of replicas to deploy
        type: string
        default: '2'

jobs:
  build:
    # see https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-22/20230109.1

    steps:
      # We need fetch-depth: 0 to include the refs. 
      # We are going to commit the version of the service in the final step.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Verify
        uses: syltek/anemone-workflows/.github/actions/maven-build@main
        with:
          java_version: ${{ inputs.java_version }}
          nexus_user: ${{ secrets.nexus_user }}
          nexus_password: ${{ secrets.nexus_password }}
          branch: ${{ github.base_ref }}

      - name: Extract version
        id: version
        uses: syltek/anemone-workflows/.github/actions/anemone-version@main
        with:
          branch_name: ${{ github.ref_name }}

      - name: Docker build
        id: docker-build
        uses: syltek/anemone-workflows/.github/actions/docker-build@main
        with:
          version: ${{ steps.version.outputs.version }}
          dockernexus_username: ${{ secrets.dockernexus_username }}
          dockernexus_token: ${{ secrets.dockernexus_token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: generate_token
        uses: syltek/frontend-workflows/github-app-token@main
        with:
          private-key: ${{ secrets.PLAYTOMIC_BOT_APP_PRIVATE_KEY }}

      - name: Commit version
        id: commit-version
        uses: syltek/anemone-workflows/.github/actions/commit-version@main
        with:
          version: ${{ steps.version.outputs.version }}
          github_token: ${{ steps.generate_token.outputs.token }}
          branch_name: ${{ github.ref_name }}
          
    outputs:
      version: ${{ steps.version.outputs.version }}
      docker_registry: ${{ steps.docker-build.outputs.docker_registry }}

  self-hosted-deploy:
    if: ${{ github.ref_name != 'develop' }}
    needs: build
    runs-on: self-hosted
    env:
      DOMAIN: 'anemone'

    steps:
      - uses: actions/checkout@v3
      - uses: syltek/anemone-workflows/.github/actions/swarm-deploy@main
        with:
          version: ${{ needs.build.outputs.version }}
          replicas: ${{ inputs.replicas }}
          docker_registry: ${{ needs.build.outputs.docker_registry }}
          docker_username: ${{ secrets.dockernexus_username }}
          docker_password: ${{ secrets.dockernexus_token }}
          aws_docker_host_dev: ${{ secrets.aws_docker_host_dev }}
          aws_docker_host_pro: ${{ secrets.aws_docker_host_pro }}
