# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy Anemone services

on:
  workflow_call:
    secrets:
      nexus_user:
        required: true
        description: User to login into Nexus mvn
      nexus_password:
        required: true
        description: Password to login into Nexus
      dockernexus_username:
        required: true
        description: Username to login into Nexus
      dockernexus_token:
        required: true
        description: Password to login into Nexus
    inputs:
      java_version:
        required: true
        description: Java version to use
        type: string
      replicas:
        required: false
        description: The number of replicas to deploy
        type: string
        default: '2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Build and Verify
        uses: syltek/workflows/.github/actions/maven-build@main
        with:
          java_version: ${{ inputs.java_version }}
          nexus_user: ${{ secrets.nexus_user }}
          nexus_password: ${{ secrets.nexus_password }}
          branch: ${{ github.base_ref }}

      - name: Extract version
        id: version
        uses: syltek/workflows/.github/actions/anemone-version@main
        with:
          branch_name: ${{ github.ref_name }}

      - name: Docker build
        id: docker-build
        uses: syltek/workflows/.github/actions/docker-build@main
        with:
          version: ${{ steps.version.outputs.version }}
          dockernexus_username: ${{ secrets.dockernexus_username }}
          dockernexus_token: ${{ secrets.dockernexus_token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      version: ${{ steps.version.outputs.version }}
      docker_registry: ${{ steps.docker-build.outputs.docker_registry }}

  self-hosted-deploy:
    needs: build
    runs-on: self-hosted
    env:
      DOMAIN: 'anemone'

    steps:
      - uses: syltek/workflows/.github/actions/swarm-deploy@main
        with:
          version: ${{ needs.build.outputs.version }}
          replicas: ${{ inputs.replicas }}
          docker_registry: ${{ needs.build.outputs.docker_registry }}
          docker_username: ${{ secrets.dockernexus_username }}
          docker_password: ${{ secrets.dockernexus_token }}
