name: Build Anemone services

on:
  workflow_call:
    secrets:
      nexus_user:
        required: true
        description: User to login into Nexus
      nexus_password:
        required: true
        description: Password to login into Nexus
    inputs:
      java_version:
        required: true
        description: Java version to use
        type: string
      deploy:
        required: false
        description: Whether to deploy the artifact
        type: string
        default: false
      validate-before-compile:
        required: false
        description: Whether to validate the project before the mvn compile
        type: string
        default: true
      validate-after-verify:
        required: false
        description: Whether to validate the project after the mvn verify
        type: string
        default: false

jobs:
  build:
    if: ${{ github.event.commits[0].author.username }} != 'argocd-image-updater'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: branch-name
        run: |
          if [ ${{github.event_name}} == "push" ]; then
            echo "::set-output name=branch_name::${{ github.ref_name }}"
          elif [ ${{github.event_name}} == "pull_request" ]; then
            echo "::set-output name=branch_name::${{ github.base_ref }}"
          fi

      - uses: syltek/anemone-workflows/.github/actions/maven-build@main
        with:
          java_version: ${{ inputs.java_version }}
          nexus_user: ${{ secrets.nexus_user }}
          nexus_password: ${{ secrets.nexus_password }}
          branch: ${{ steps.branch-name.outputs.branch_name }}
          deploy: ${{ inputs.deploy }}
          validate-before-compile: ${{ inputs.validate-before-compile }}
          validate-after-verify: ${{ inputs.validate-after-verify }}